// Generated by CoffeeScript 1.10.0
(function() {
  var canvas, context, img;

  canvas = document.getElementById('canvas');

  context = canvas.getContext('2d');

  canvas.width = window.innerWidth;

  canvas.height = window.innerHeight;

  img = new Image();

  img.src = "img/player.png";

  img.onload = function() {
    return context.drawImage(img, 10, 10, 32, 32);
  };

}).call(this);
