// Generated by CoffeeScript 1.10.0
(function() {
  var A, D, S, W, calcSpeed, canvas, context, img, lastKeyPressed, lastUpdate, processInput, render, run, update, x, y;

  canvas = document.getElementById('canvas');

  context = canvas.getContext('2d');

  canvas.width = window.innerWidth;

  canvas.height = window.innerHeight;

  img = new Image();

  img.src = "img/player.png";

  img.onload = function() {
    return context.drawImage(img, 10, 10, 32, 32);
  };

  lastKeyPressed = 0;

  lastUpdate = 0;

  x = 0;

  y = 0;

  A = 97;

  D = 100;

  S = 115;

  W = 119;

  document.body.onkeypress = function(e) {
    return processInput(e.keyCode || e.which);
  };

  processInput = function(keyCode) {
    return lastKeyPressed = keyCode;
  };

  calcSpeed = function(delta, pixelsPerSec) {
    return (pixelsPerSec * delta) / 1000;
  };

  update = function(delta) {
    if (lastKeyPressed === A) {
      return x -= calcSpeed(delta, 100);
    } else if (lastKeyPressed === D) {
      return x += calcSpeed(delta, 100);
    } else if (lastKeyPressed === W) {
      return y -= calcSpeed(delta, 100);
    } else if (lastKeyPressed === S) {
      return y += calcSpeed(delta, 100);
    } else {
      return lastKeyPressed = null;
    }
  };

  render = function() {
    context.clearRect(0, 0, canvas.width, canvas.height);
    return context.drawImage(img, x, y, 32, 32);
  };

  run = function() {
    var delta, time;
    time = new Date().getTime();
    delta = time - lastUpdate;
    update(delta);
    render();
    lastUpdate = new Date().getTime();
    return window.requestAnimationFrame(run);
  };

  lastUpdate = new Date().getTime();

  window.requestAnimationFrame(run);

}).call(this);
